package com.azizi.filemanager;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.*;
import java.io.*;
import java.util.*;
import java.util.zip.*;

public class MainActivity extends AppCompatActivity {
    LinearLayout root, toolbar, actions; TextView pathView, empty; EditText search; RecyclerView list; FileAdapter adapter;
    File current; ArrayList<File> clipboard=new ArrayList<>(); boolean cut=false; boolean showingHidden=false;
    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(0xFFFFFFFF); getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR); setTitle("مدير ملفات العزي"); StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder().build()); buildUi(); current=Environment.getExternalStorageDirectory(); checkStorage(); showDir(current);}
    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(0xFF202124);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(10),0,dp(10),0);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setMinHeight(dp(44));return b;}
    void buildUi(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setBackgroundColor(0xFFF7F8FA);setContentView(root);toolbar=new LinearLayout(this);toolbar.setGravity(Gravity.CENTER_VERTICAL);toolbar.setPadding(dp(8),dp(4),dp(8),dp(4));toolbar.setBackgroundColor(Color.WHITE);Button up=btn("⬆");up.setOnClickListener(v->{if(current!=null&&current.getParentFile()!=null)showDir(current.getParentFile());});toolbar.addView(up,new LinearLayout.LayoutParams(dp(52),dp(50)));pathView=tv("مدير الملفات",18);pathView.setTypeface(null,1);toolbar.addView(pathView,new LinearLayout.LayoutParams(0,dp(50),1));Button more=btn("⋮");more.setOnClickListener(v->menu());toolbar.addView(more,new LinearLayout.LayoutParams(dp(52),dp(50)));root.addView(toolbar);search=new EditText(this);search.setHint("بحث في المجلد الحالي…");search.setSingleLine();search.setPadding(dp(14),0,dp(14),0);root.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){if(adapter!=null)adapter.filter(s.toString());}public void afterTextChanged(android.text.Editable e){}});actions=new LinearLayout(this);actions.setPadding(dp(6),dp(2),dp(6),dp(2));String[] as={"مجلد جديد","لصق","إظهار المخفي"};for(String s:as){Button b=btn(s);actions.addView(b,new LinearLayout.LayoutParams(0,dp(45),1));if(s.equals("مجلد جديد"))b.setOnClickListener(v->newFolder());else if(s.equals("لصق"))b.setOnClickListener(v->paste());else b.setOnClickListener(v->{showingHidden=!showingHidden;showDir(current);});}root.addView(actions);list=new RecyclerView(this);list.setLayoutManager(new LinearLayoutManager(this));root.addView(list,new LinearLayout.LayoutParams(-1,0,1));empty=tv("لا توجد ملفات",16);empty.setGravity(Gravity.CENTER);root.addView(empty,new LinearLayout.LayoutParams(-1,dp(70)));empty.setVisibility(View.GONE);}
    void checkStorage(){if(Build.VERSION.SDK_INT>=30&&!Environment.isExternalStorageManager()){new AlertDialog.Builder(this).setTitle("صلاحية الملفات").setMessage("يحتاج مدير الملفات إلى صلاحية الوصول إلى جميع الملفات لكي يعمل مثل مدير الملفات الكامل.").setPositiveButton("فتح الإعدادات",(d,w)->{try{startActivity(new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));}}).setNegativeButton("لاحقًا",null).show();}}
    void showDir(File dir){if(dir==null)return;current=dir;pathView.setText(dir.getAbsolutePath());File[] fs=dir.listFiles();ArrayList<File> out=new ArrayList<>();if(fs!=null)for(File f:fs)if(showingHidden||!f.isHidden())out.add(f);Collections.sort(out,(a,b)->{if(a.isDirectory()!=b.isDirectory())return a.isDirectory()?-1:1;return a.getName().compareToIgnoreCase(b.getName());});adapter=new FileAdapter(out);list.setAdapter(adapter);empty.setVisibility(out.isEmpty()?View.VISIBLE:View.GONE);}
    void newFolder(){final EditText e=new EditText(this);e.setHint("اسم المجلد");new AlertDialog.Builder(this).setTitle("إنشاء مجلد").setView(e).setPositiveButton("إنشاء",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty()){File f=new File(current,n);if(!f.mkdir())toast("تعذر إنشاء المجلد");showDir(current);}}).setNegativeButton("إلغاء",null).show();}
    void paste(){if(clipboard.isEmpty()){toast("لا يوجد شيء في الحافظة");return;}new Thread(()->{for(File f:clipboard)copyRecursive(f,new File(current,f.getName()));if(cut)for(File f:clipboard)deleteRecursive(f);runOnUiThread(()->{clipboard.clear();cut=false;showDir(current);toast("تم اللصق");});}).start();}
    void copyRecursive(File src,File dst){try{if(src.isDirectory()){if(!dst.exists())dst.mkdirs();File[] a=src.listFiles();if(a!=null)for(File x:a)copyRecursive(x,new File(dst,x.getName()));}else{try(InputStream in=new FileInputStream(src);OutputStream out=new FileOutputStream(dst)){byte[] buf=new byte[65536];int n;while((n=in.read(buf))>0)out.write(buf,0,n);}}}catch(Exception e){}}
    void deleteRecursive(File f){if(f.isDirectory()){File[] a=f.listFiles();if(a!=null)for(File x:a)deleteRecursive(x);}f.delete();}
    void menu(){String[] m={"المجلد الرئيسي","المجلد الجذر /storage","بحث شامل","إعدادات الصلاحيات","حول التطبيق"};new AlertDialog.Builder(this).setTitle("القائمة").setItems(m,(d,w)->{if(w==0)showDir(Environment.getExternalStorageDirectory());else if(w==1)showDir(new File("/storage"));else if(w==2)globalSearch();else if(w==3)checkStorage();else new AlertDialog.Builder(this).setTitle("مدير ملفات العزي").setMessage("مدير ملفات Native لنظام Android 11/12\nنسخة 1.0.0").setPositiveButton("حسنًا",null).show();}).show();}
    void globalSearch(){final EditText e=new EditText(this);e.setHint("اسم الملف");new AlertDialog.Builder(this).setTitle("بحث شامل").setView(e).setPositiveButton("بحث",(d,w)->{String q=e.getText().toString().toLowerCase();ArrayList<File> r=new ArrayList<>();walk(Environment.getExternalStorageDirectory(),q,r,0);adapter=new FileAdapter(r);list.setAdapter(adapter);pathView.setText("نتائج البحث: "+r.size());}).setNegativeButton("إلغاء",null).show();}
    void walk(File dir,String q,ArrayList<File> r,int depth){if(depth>20||dir==null)return;File[] a=dir.listFiles();if(a==null)return;for(File f:a){if(f.getName().toLowerCase().contains(q))r.add(f);if(f.isDirectory()&&!f.isHidden())walk(f,q,r,depth+1);if(r.size()>500)return;}}
    void itemMenu(File f){String[] m={"فتح","نسخ","قص","إعادة تسمية","حذف","مشاركة","معلومات","ضغط ZIP","فك ZIP"};new AlertDialog.Builder(this).setTitle(f.getName()).setItems(m,(d,w)->{switch(w){case 0:open(f);break;case 1:clipboard.clear();clipboard.add(f);cut=false;toast("تم النسخ");break;case 2:clipboard.clear();clipboard.add(f);cut=true;toast("تم القص");break;case 3:rename(f);break;case 4:confirmDelete(f);break;case 5:share(f);break;case 6:info(f);break;case 7:zip(f);break;case 8:unzip(f);break;}}).show();}
    void open(File f){if(f.isDirectory())showDir(f);else try{Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(Uri.fromFile(f),mime(f));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception e){toast("لا يوجد تطبيق لفتح هذا الملف");}}
    String mime(File f){String n=f.getName().toLowerCase();if(n.endsWith(".jpg")||n.endsWith(".jpeg"))return"image/jpeg";if(n.endsWith(".png"))return"image/png";if(n.endsWith(".mp4"))return"video/mp4";if(n.endsWith(".mp3"))return"audio/*";if(n.endsWith(".pdf"))return"application/pdf";if(n.endsWith(".txt"))return"text/plain";return"*/*";}
    void rename(File f){EditText e=new EditText(this);e.setText(f.getName());new AlertDialog.Builder(this).setTitle("إعادة تسمية").setView(e).setPositiveButton("حفظ",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty()&&!n.equals(f.getName()))f.renameTo(new File(f.getParent(),n));showDir(current);}).setNegativeButton("إلغاء",null).show();}
    void confirmDelete(File f){new AlertDialog.Builder(this).setTitle("حذف").setMessage("حذف «"+f.getName()+"» نهائيًا؟").setPositiveButton("حذف",(d,w)->{deleteRecursive(f);showDir(current);}).setNegativeButton("إلغاء",null).show();}
    void share(File f){try{Intent i=new Intent(Intent.ACTION_SEND);i.setType(mime(f));i.putExtra(Intent.EXTRA_STREAM,Uri.fromFile(f));startActivity(Intent.createChooser(i,"مشاركة الملف"));}catch(Exception e){toast("تعذر المشاركة");}}
    void info(File f){String s="الاسم: "+f.getName()+"\nالمسار: "+f.getAbsolutePath()+"\nالحجم: "+size(f)+"\nالنوع: "+(f.isDirectory()?"مجلد":"ملف")+"\nآخر تعديل: "+new Date(f.lastModified());new AlertDialog.Builder(this).setTitle("معلومات الملف").setMessage(s).setPositiveButton("حسنًا",null).show();}
    String size(File f){long n=f.isDirectory()?dirSize(f):f.length();String[] u={"B","KB","MB","GB"};int i=0;double x=n;while(x>=1024&&i<3){x/=1024;i++;}return String.format(Locale.US,"%.1f %s",x,u[i]);}long dirSize(File f){long s=0;File[] a=f.listFiles();if(a!=null)for(File x:a)s+=x.isDirectory()?dirSize(x):x.length();return s;}
    void zip(File f){File out=new File(f.getParent(),f.getName()+".zip");try(ZipOutputStream z=new ZipOutputStream(new FileOutputStream(out))){zipAdd(z,f,f.getName());toast("تم إنشاء ZIP");showDir(current);}catch(Exception e){toast("فشل الضغط");}}
    void zipAdd(ZipOutputStream z,File f,String name)throws Exception{if(f.isDirectory()){File[] a=f.listFiles();if(a==null||a.length==0){z.putNextEntry(new ZipEntry(name+"/"));z.closeEntry();}else for(File x:a)zipAdd(z,x,name+"/"+x.getName());}else{z.putNextEntry(new ZipEntry(name));try(InputStream in=new FileInputStream(f)){byte[] b=new byte[65536];int n;while((n=in.read(b))>0)z.write(b,0,n);}z.closeEntry();}}
    void unzip(File f){if(!f.getName().toLowerCase().endsWith(".zip")){toast("اختر ملف ZIP");return;}File out=new File(current,f.getName().substring(0,f.getName().length()-4));if(!out.exists())out.mkdirs();try(ZipInputStream z=new ZipInputStream(new FileInputStream(f))){ZipEntry e;byte[] b=new byte[65536];while((e=z.getNextEntry())!=null){File x=new File(out,e.getName());if(e.isDirectory())x.mkdirs();else{File p=x.getParentFile();if(p!=null)p.mkdirs();try(OutputStream o=new FileOutputStream(x)){int n;while((n=z.read(b))>0)o.write(b,0,n);}}}toast("تم فك الضغط");showDir(current);}catch(Exception e){toast("فشل فك الضغط");}}
    void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}
    class FileAdapter extends RecyclerView.Adapter<FileAdapter.VH>{ArrayList<File> all,shown;FileAdapter(ArrayList<File> a){all=new ArrayList<>(a);shown=new ArrayList<>(a);}void filter(String q){shown.clear();q=q.toLowerCase();for(File f:all)if(f.getName().toLowerCase().contains(q))shown.add(f);notifyDataSetChanged();}public VH onCreateViewHolder(android.view.ViewGroup p,int v){LinearLayout r=new LinearLayout(MainActivity.this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(10),dp(4),dp(10),dp(4));TextView icon=tv("",25);TextView name=tv("",16);name.setTypeface(null,1);TextView sub=tv("",12);LinearLayout texts=new LinearLayout(MainActivity.this);texts.setOrientation(LinearLayout.VERTICAL);texts.addView(name,new LinearLayout.LayoutParams(0,dp(32),1));texts.addView(sub,new LinearLayout.LayoutParams(0,dp(25),1));r.addView(icon,new LinearLayout.LayoutParams(dp(52),dp(62)));r.addView(texts,new LinearLayout.LayoutParams(0,dp(72),1));return new VH(r,icon,name,sub);}public void onBindViewHolder(VH h,int p){File f=shown.get(p);h.icon.setText(f.isDirectory()?"📁":icon(f));h.name.setText(f.getName());h.sub.setText(f.isDirectory()?"مجلد":size(f));h.itemView.setOnClickListener(v->open(f));h.itemView.setOnLongClickListener(v->{itemMenu(f);return true;});}String icon(File f){String n=f.getName().toLowerCase();if(n.endsWith(".jpg")||n.endsWith(".png")||n.endsWith(".jpeg"))return"🖼️";if(n.endsWith(".mp3"))return"🎵";if(n.endsWith(".mp4"))return"🎬";if(n.endsWith(".zip"))return"🗜️";if(n.endsWith(".pdf"))return"📕";return"📄";}public int getItemCount(){return shown.size();}class VH extends RecyclerView.ViewHolder{TextView icon,name,sub;VH(View v,TextView i,TextView n,TextView s){super(v);icon=i;name=n;sub=s;}}}
}
